### ISSUE TITLE
Translate filter

### ISSUE THREAD

**Issue by jordansissel** [alcanzar/logstash-filter-augment#3]
Howdy! I saw this got published and wanted to check it out.

It looks to me that this filter and the [translate filter](https://www.elastic.co/guide/en/logstash/current/plugins-filters-translate.html) are very similar (both are lookups sourced from csv, json, or yaml).

Do you think these two efforts could be combined?

It's totally OK to keep this plugin separate, too. I wanted to offer that we could consolidate efforts and reduce the number of similar plugins, if you think that your augment filter is different from the translate filter.

**Comment by alcanzar** [comment]
I did base my filter on translate, but translate seems to be geared more towards adding a single value from a lookup.  Mine is designed to add multiple fields based on a lookup.  Adding my functionality to translate is possible, but it was beyond what I wanted to do when I wrote it.

**Comment by jordansissel** [comment]
I do multiple value lookups with translate, though maybe I am using the term 'multiple lookup' differently -- here's what I Mean.

I had some data with US zip codes, and I wanted to map them in Kibana, so I made a YAML file with zip code to coordinates that looked something like this:

```
90210:
  latitude: 34.102144
  longitude: 118.416217
```

The above would let me use the translate filter to lookup "90210" (a zip code) and get a map of latitude+longitude.

**Comment by alcanzar** [comment]
my data was coming in as a CSV file and that isn't supported by translate.  I added the JSON/YAML support on as more of a "why not".

**Comment by alcanzar** [comment]
In my other use case, I was provided a "codes.json" which was an array of objects.  I needed to augment the fields from that array onto the events.

For example:
[{"code":"A","name":"Code A","value":10},{"code":"B","name":"Code B","value":20}]

So I used my filter to do a lookup on code and augment in the name/value.

**Comment by jordansissel** [comment]
@alcanzar aah, that makes sense. If you'd like (and there's no pressure here, and no wrong answer), we can add these two things (csv, and json top-level-array) into the translate filter.

Regardless of what you choose, I want to thank you for publishing this plugin and also for working to make Logstash more useful for everyone :)

**Comment by alcanzar** [comment]
If I have time, I'll work on adding the functionality to translate and submit some PR's.  I've got quite a few test cases covering my needs in my code, so it shouldn't be too much of an effort.  I have a much deeper appreciation of the effort involved now :)

**Comment by jordansissel** [comment]
Sounds good -- if you start work on it (even just filing the issue), I'll keep an eye out for it, so I can help if desired :)
